### ISSUE TITLE
Unable to reload outside of root in production

### ISSUE THREAD

**Issue by stevemcd87** [stevemcd87/review#1]
When a user reloads anywhere other then the root domain it produces ACCESS DENIED error

**Comment by stevemcd87** [comment]
Needed to add an additional source address in the amplify console Redirects section.

https://github.com/aws-amplify/amplify-js/issues/2545

**Comment by codabulo** [comment]
If the issue is with single-web-page apps (such as reactjs), see the Amplify DOCS: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html
see: "Redirects for Single Page Web Apps (SPA)"

Solution that worked for me:
In  AWS Console > Amplify > Rewrites and redirects...
Edit the redirects to create a redirect with:
Source address: </^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>
Target address: /index.html
Type: 200

Why does this work? You need to let through requests ending in js, json, etc, so a simple <*> won't work here...
